### ISSUE TITLE
InvalidArgumentError : buffer_size must be greater than zero

### ISSUE THREAD

**Issue by pongopal** [gvalvano/sdnet#1]
InvalidArgumentError (see above for traceback): buffer_size must be greater than zero.
	 [[node acdc_data_2/ShuffleDataset (defined at /sdnet-master/data_interface/interfaces/acdc_unsup_interface.py:177) ]]
	 [[node acdc_data_2/seed2_1 (defined at /sdnet-master/data_interface/interfaces/acdc_unsup_interface.py:156) ]]

**Comment by gvalvano** [comment]
It seems that you are not loading the data correctly. In fact, if your dataset is empty, then you cannot shuffle it (`train_data.shuffle()`). 
Generally speaking, the unsupervised pipeline builds a dataset of paths, and then it maps a parsing function (`self.data_parser()`) on each path, which returns the associated training volume. If you check the class method: `__init__()`, you can see how this list of paths is produced in the first place: you want your volumes to be numpy arrays with names: 

> 'patient' + pt_number + '_4d_preproc.npy'

**Comment by pongopal** [comment]
Data is already in the specified folder with the specified format, "'patient' + pt_number + '_4d_preproc.npy'. Still same error!

**Comment by gvalvano** [comment]
That sounds really odd! Have you tried to print the file name and check if the path is correct? (e.g. in your terminal write `ls printed/path/to/file.npy`). Sometimes even a small typo can mess things up... Another thing to double-check would be the shapes: these are of the form [batch_size, image_size_0, image_size_1, n_channels]. For the images, n_channels is =1, for segmentations, this is the number of classes, with the background first.

Let me know how it goes. If you still cannot solve the problem, feel free to attach the full error stack to the conversation :)

**Comment by pongopal** [comment]
Colocations handled automatically by placer.
Building the computation graph...
RUN_ID = SDTNet
 --> Repeat the input indefinitely  = True
Define input pipeline for adversarial discriminator data...
 --> Repeat the input indefinitely  = True
Define input pipeline for unsupervised data...
/media/leon/extra/sdnet/code/data/acdc_data/train
[]
/media/leon/extra/sdnet/code/data/acdc_data/validation
['/media/leon/extra/sdnet/code/data/acdc_data/validation/patient001', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient017', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient018', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient022', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient025', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient027', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient032', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient044', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient049', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient057', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient079', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient081', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient084', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient095', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient096']
[]
['/media/leon/extra/sdnet/code/data/acdc_data/validation/patient001/patient001_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient017/patient017_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient018/patient018_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient022/patient022_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient025/patient025_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient027/patient027_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient032/patient032_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient044/patient044_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient049/patient049_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient057/patient057_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient079/patient079_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient081/patient081_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient084/patient084_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient095/patient095_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient096/patient096_4d_preproc.npy']
<DatasetV1Adapter shapes: (), types: tf.float32>
WARNING:tensorflow:From /media/leon/extra/sdnet/code/data_interface/interfaces/acdc_unsup_interface.py:147: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, use
    tf.py_function, which takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    
 --> Repeat the input indefinitely  = True
WARNING:tensorflow:From /media/leon/extra/sdnet/code/architectures/unet.py:123: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.conv2d instead.
WARNING:tensorflow:From /media/leon/extra/sdnet/code/architectures/unet.py:124: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.batch_normalization instead.
WARNING:tensorflow:From /media/leon/extra/sdnet/code/architectures/unet.py:132: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.max_pooling2d instead.
WARNING:tensorflow:From /media/leon/extra/sdnet/code/architectures/modality_encoder.py:131: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /media/leon/extra/sdnet/code/architectures/modality_encoder.py:132: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.
WARNING:tensorflow:From /media/leon/extra/sdnet/code/idas/losses/tf_losses.py:44: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.


Starting network training... Number of epochs to train: 10
Tensorboard verbose mode: True
Tensorboard dir: ./results/graphs/SDTNet/convnet
Data augmentation: True, Data standardization: False.
Model already trained for 0 epochs.

Running RoutineCallback...
Done.
________________________________________
EPOCH 1 - SDTNet : 
  Progress:    [=> Traceback (most recent call last):
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: buffer_size must be greater than zero.
	 [[{{node acdc_data_2/ShuffleDataset}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 34, in <module>
    model.train(n_epochs=N_EPOCHS)
  File "/media/leon/extra/sdnet/code/model.py", line 632, in train
    t_step = self.train_one_epoch(sess, iterator_init_list, writer, t_step, caller, seed)
  File "/media/leon/extra/sdnet/code/model.py", line 417, in train_one_epoch
    sess.run(init, feed_dict={self.global_seed: seed})
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: buffer_size must be greater than zero.
	 [[node acdc_data_2/ShuffleDataset (defined at /media/leon/extra/sdnet/code/data_interface/interfaces/acdc_unsup_interface.py:182) ]]

Caused by op 'acdc_data_2/ShuffleDataset', defined at:
  File "train.py", line 32, in <module>
    model.build()
  File "/media/leon/extra/sdnet/code/model.py", line 113, in build
    self.get_data()
  File "/media/leon/extra/sdnet/code/model.py", line 137, in get_data
    super(Model, self).get_acdc_unsup_data(data_path=self.acdc_data_path, repeat=True, seed=self.global_seed)
  File "/media/leon/extra/sdnet/code/data_interface/dataset_wrapper.py", line 109, in get_acdc_unsup_data
    seed=seed
  File "/media/leon/extra/sdnet/code/data_interface/interfaces/acdc_unsup_interface.py", line 182, in get_data
    train_init = iterator.make_initializer(train_data)  # initializer for train_data
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 360, in make_initializer
    dataset._as_variant_tensor(), self._iterator_resource, name=name)  # pylint: disable=protected-access
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1630, in _as_variant_tensor
    return self._dataset._as_variant_tensor()  # pylint: disable=protected-access
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2502, in _as_variant_tensor
    self._input_dataset._as_variant_tensor(),  # pylint: disable=protected-access
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1630, in _as_variant_tensor
    return self._dataset._as_variant_tensor()  # pylint: disable=protected-access
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/experimental/ops/batching.py", line 375, in _as_variant_tensor
    self._input_dataset._as_variant_tensor(),  # pylint: disable=protected-access
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/experimental/ops/batching.py", line 544, in _as_variant_tensor
    return self._input_dataset._as_variant_tensor()  # pylint: disable=protected-access
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1630, in _as_variant_tensor
    return self._dataset._as_variant_tensor()  # pylint: disable=protected-access
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2740, in _as_variant_tensor
    input_t = self._input_dataset._as_variant_tensor()  # pylint: disable=protected-access
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1630, in _as_variant_tensor
    return self._dataset._as_variant_tensor()  # pylint: disable=protected-access
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2335, in _as_variant_tensor
    self._input_dataset._as_variant_tensor(),  # pylint: disable=protected-access
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1630, in _as_variant_tensor
    return self._dataset._as_variant_tensor()  # pylint: disable=protected-access
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2778, in _as_variant_tensor
    input_t = self._input_dataset._as_variant_tensor()
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1630, in _as_variant_tensor
    return self._dataset._as_variant_tensor()  # pylint: disable=protected-access
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2778, in _as_variant_tensor
    input_t = self._input_dataset._as_variant_tensor()
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1630, in _as_variant_tensor
    return self._dataset._as_variant_tensor()  # pylint: disable=protected-access
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2443, in _as_variant_tensor
    **flat_structure(self))
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 4416, in shuffle_dataset
    name=name)
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): buffer_size must be greater than zero.
	 [[node acdc_data_2/ShuffleDataset (defined at /media/leon/extra/sdnet/code/data_interface/interfaces/acdc_unsup_interface.py:182) ]]

**Comment by gvalvano** [comment]
It seems that the paths to the validation data are correct, but you are also printing an empty list. Can you check why is that?

**Comment by pongopal** [comment]
You are right! Now I have fixed the path but it shows another error:

----------
WARNING:tensorflow:From /home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Building the computation graph...
RUN_ID = SDTNet
Define input pipeline for supervised data...
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    model.build()
  File "/media/leon/extra/SemiSSET/code/model.py", line 114, in build
    self.get_data()
  File "/media/leon/extra/SemiSSET/code/model.py", line 132, in get_data
    super(Model, self).get_acdc_sup_data(data_path=self.acdc_data_path, repeat=False, seed=self.global_seed)
  File "/media/leon/extra/SemiSSET/code/data_interface/dataset_wrapper.py", line 43, in get_acdc_sup_data
    seed=seed
ValueError: not enough values to unpack (expected 5, got 4)

**Comment by gvalvano** [comment]
I guess your sess.run() returns 4 elements, but you are assigning them to 5 variables (on the left side of "=")

**Comment by pongopal** [comment]
I had changed the 5 elements to 4, still have the same issue

**Comment by gvalvano** [comment]
@pongopal I cannot help you without knowing exactly what you've modified in the code. If you don't mind, could you share a snippet of the pice of code raising the error? Moreover, I would invite you to open a separate thread because - apparently - the original problem was solved :) If that's ok, you can open a new thread with the code so that I can close this one and get back to you there!

**Comment by pongopal** [comment]
Thank you, I am closing this session

**Comment by JackHeroFly** [comment]
> 
> 
> Colocations handled automatically by placer.
> Building the computation graph...
> RUN_ID = SDTNet
> --> Repeat the input indefinitely = True
> Define input pipeline for adversarial discriminator data...
> --> Repeat the input indefinitely = True
> Define input pipeline for unsupervised data...
> /media/leon/extra/sdnet/code/data/acdc_data/train
> []
> /media/leon/extra/sdnet/code/data/acdc_data/validation
> ['/media/leon/extra/sdnet/code/data/acdc_data/validation/patient001', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient017', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient018', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient022', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient025', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient027', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient032', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient044', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient049', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient057', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient079', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient081', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient084', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient095', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient096']
> []
> ['/media/leon/extra/sdnet/code/data/acdc_data/validation/patient001/patient001_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient017/patient017_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient018/patient018_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient022/patient022_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient025/patient025_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient027/patient027_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient032/patient032_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient044/patient044_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient049/patient049_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient057/patient057_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient079/patient079_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient081/patient081_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient084/patient084_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient095/patient095_4d_preproc.npy', '/media/leon/extra/sdnet/code/data/acdc_data/validation/patient096/patient096_4d_preproc.npy']
> <DatasetV1Adapter shapes: (), types: tf.float32>
> WARNING:tensorflow:From /media/leon/extra/sdnet/code/data_interface/interfaces/acdc_unsup_interface.py:147: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> tf.py_func is deprecated in TF V2. Instead, use
> tf.py_function, which takes a python function which manipulates tf eager
> tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
> an ndarray (just call tensor.numpy()) but having access to eager tensors
> means `tf.py_function`s can use accelerators such as GPUs as well as
> being differentiable using a gradient tape.
> 
> --> Repeat the input indefinitely = True
> WARNING:tensorflow:From /media/leon/extra/sdnet/code/architectures/unet.py:123: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.conv2d instead.
> WARNING:tensorflow:From /media/leon/extra/sdnet/code/architectures/unet.py:124: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.batch_normalization instead.
> WARNING:tensorflow:From /media/leon/extra/sdnet/code/architectures/unet.py:132: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.max_pooling2d instead.
> WARNING:tensorflow:From /media/leon/extra/sdnet/code/architectures/modality_encoder.py:131: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.flatten instead.
> WARNING:tensorflow:From /media/leon/extra/sdnet/code/architectures/modality_encoder.py:132: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.dense instead.
> WARNING:tensorflow:From /media/leon/extra/sdnet/code/idas/losses/tf_losses.py:44: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.cast instead.
> WARNING:tensorflow:From /home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.cast instead.
> 
> Starting network training... Number of epochs to train: 10
> Tensorboard verbose mode: True
> Tensorboard dir: ./results/graphs/SDTNet/convnet
> Data augmentation: True, Data standardization: False.
> Model already trained for 0 epochs.
> 
> Running RoutineCallback...
> Done.
> 
> EPOCH 1 - SDTNet :
> Progress: [=> Traceback (most recent call last):
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
> return fn(*args)
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
> options, feed_dict, fetch_list, target_list, run_metadata)
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
> run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: buffer_size must be greater than zero.
> [[{{node acdc_data_2/ShuffleDataset}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "train.py", line 34, in
> model.train(n_epochs=N_EPOCHS)
> File "/media/leon/extra/sdnet/code/model.py", line 632, in train
> t_step = self.train_one_epoch(sess, iterator_init_list, writer, t_step, caller, seed)
> File "/media/leon/extra/sdnet/code/model.py", line 417, in train_one_epoch
> sess.run(init, feed_dict={self.global_seed: seed})
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
> run_metadata_ptr)
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
> feed_dict_tensor, options, run_metadata)
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
> run_metadata)
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: buffer_size must be greater than zero.
> [[node acdc_data_2/ShuffleDataset (defined at /media/leon/extra/sdnet/code/data_interface/interfaces/acdc_unsup_interface.py:182) ]]
> 
> Caused by op 'acdc_data_2/ShuffleDataset', defined at:
> File "train.py", line 32, in
> model.build()
> File "/media/leon/extra/sdnet/code/model.py", line 113, in build
> self.get_data()
> File "/media/leon/extra/sdnet/code/model.py", line 137, in get_data
> super(Model, self).get_acdc_unsup_data(data_path=self.acdc_data_path, repeat=True, seed=self.global_seed)
> File "/media/leon/extra/sdnet/code/data_interface/dataset_wrapper.py", line 109, in get_acdc_unsup_data
> seed=seed
> File "/media/leon/extra/sdnet/code/data_interface/interfaces/acdc_unsup_interface.py", line 182, in get_data
> train_init = iterator.make_initializer(train_data) # initializer for train_data
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 360, in make_initializer
> dataset._as_variant_tensor(), self._iterator_resource, name=name) # pylint: disable=protected-access
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1630, in _as_variant_tensor
> return self._dataset._as_variant_tensor() # pylint: disable=protected-access
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2502, in _as_variant_tensor
> self._input_dataset._as_variant_tensor(), # pylint: disable=protected-access
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1630, in _as_variant_tensor
> return self._dataset._as_variant_tensor() # pylint: disable=protected-access
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/experimental/ops/batching.py", line 375, in _as_variant_tensor
> self._input_dataset._as_variant_tensor(), # pylint: disable=protected-access
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/experimental/ops/batching.py", line 544, in _as_variant_tensor
> return self._input_dataset._as_variant_tensor() # pylint: disable=protected-access
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1630, in _as_variant_tensor
> return self._dataset._as_variant_tensor() # pylint: disable=protected-access
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2740, in _as_variant_tensor
> input_t = self._input_dataset._as_variant_tensor() # pylint: disable=protected-access
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1630, in _as_variant_tensor
> return self._dataset._as_variant_tensor() # pylint: disable=protected-access
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2335, in _as_variant_tensor
> self._input_dataset._as_variant_tensor(), # pylint: disable=protected-access
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1630, in _as_variant_tensor
> return self._dataset._as_variant_tensor() # pylint: disable=protected-access
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2778, in _as_variant_tensor
> input_t = self._input_dataset._as_variant_tensor()
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1630, in _as_variant_tensor
> return self._dataset._as_variant_tensor() # pylint: disable=protected-access
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2778, in _as_variant_tensor
> input_t = self._input_dataset._as_variant_tensor()
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1630, in _as_variant_tensor
> return self._dataset._as_variant_tensor() # pylint: disable=protected-access
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2443, in _as_variant_tensor
> **flat_structure(self))
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 4416, in shuffle_dataset
> name=name)
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
> op_def=op_def)
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
> return func(*args, **kwargs)
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
> op_def=op_def)
> File "/home/leon/anaconda3/envs/forKeras/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in **init**
> self._traceback = tf_stack.extract_stack()
> 
> InvalidArgumentError (see above for traceback): buffer_size must be greater than zero.
> [[node acdc_data_2/ShuffleDataset (defined at /media/leon/extra/sdnet/code/data_interface/interfaces/acdc_unsup_interface.py:182) ]]

I also encountered this problem"InvalidArgumentError: buffer_size must be greater than zero ". How did you solve it?
